### PR TITLE
allow new lines and comments in lambda parameters

### PR DESCRIPTION
**Pull request by dten**
cc https://github.com/rust-lang/rust-enhanced/issues/284 6 and 7

image

### CODE REVIEW

**Comment by dten** [comment]
@jasonwilliams can we get some of these syntax fixes merged, the current default is far from what it will be after all these merge

**Comment by ehuss** [comment]
@dten I think Jason is on vacation for the next week, so it'll probably be delayed for a little while.

**Comment by dten** [comment]
Doh I missed that

**Comment by jasonwilliams** [comment]
Yes when I’m back I will try to merge some more of these, @dten are you able to join the official Rust discord? https://discord.gg/JTcKGAy Ping me once you’re in there.

**Comment by jasonwilliams** [comment]
@dten conflict here

**Comment by dten** [comment]
that was the world's most mundane conflict 🎉

**Comment by jasonwilliams** [comment]
@dten sorry, but as i was merging in the other PRs i caused another conflict :/

**Comment by dten** [comment]
what i didn't get was that it wasn't really a conflict, i added something to the bottom of a file, so did someone else (we both added tests) i've no idea why it would complain

**Pull request merged**
