### PR TITLE
 Update message handling for Rust 1.24. 

### LINKED ISSUE #234: It infers the wrong file path from json error msg
When I get an error like:
```
error: server\src\controllers\driver.rs:241: cannot find struct, variant or union type `Location` in this scope
```
When I click on it, it opens a non-existing file `<project_root>\server\server\src\controllers\driver.rs`
but it should instead open the right file at `<project_root>\server\src\controllers\driver.rs`.
(Btw, this project is in a workspace, of which `server` is one crate.)

### PR DESCRIPTION
**Pull request by ehuss**
Rust 1.24 introduces some breaking changes, in particular:

* All paths are now relative to the workspace root instead of the package root.
* Columns reported in macros are now 1-based (affects test output).

Fixes #234.

### CODE REVIEW

**Comment by TheIronBorn** [comment]
Could we get some eyes on this? I run into this issue daily.

**Comment by Boscop** [comment]
Do I just have to restart Sublime to get this fix?

Is there a way to update rust-enhanced without restarting sublime?

**Comment by dten** [comment]
I think technically you can disable then enable rust enhanced from the package control commands. There's also a check for updates commands if I remember correctly

**Comment by Boscop** [comment]
Ah, i just updated rust sublime but now ctrl-b doesn't do anything anymore. Ctrl shift b still opens the menu but upon choosing one entry it also doesn't build or check etc..
Why?

**Comment by Boscop** [comment]
I also tried disabling and enabling it, didn't work either..

**Comment by ehuss** [comment]
@Boscop Is there anything displayed in the Sublime console?

**Comment by TheIronBorn** [comment]
I'm also still getting the issue on `v2.7.0`.  I can still build from the menu or keyboard though.  Not seeing any unusual console stuff as far as I can tell.

**Comment by ehuss** [comment]
@TheIronBorn which issue are you having?  No messages inside a workspace?  Which version of rustc are you using?

**Comment by TheIronBorn** [comment]
I just tested with `rustc 1.25.0-nightly (0f9c78475 2018-01-17)`

**Comment by ehuss** [comment]
@TheIronBorn I think you need 2018-01-19 or newer.

**Comment by TheIronBorn** [comment]
Ah.  It works for `1.24` at least

**Comment by TheIronBorn** [comment]
Confirm it works for `rustc 1.25.0-nightly (bacb5c58d 2018-01-26)`

**Comment by Boscop** [comment]
@ehuss When I press Ctrl-B, in the console it shows this:
```
2018-01-28 05:25:48,180: 8104: DEBUG: on_window_command
2018-01-28 05:25:48,193: 8104: DEBUG: Looking for client for extension rs in D:\docs\foo\foo-server
2018-01-28 05:25:48,194: 8104: DEBUG: Extension rs is not supported yet
Exception in thread Cargo Exec:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "rust.rust_thread in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\Rust Enhanced.sublime-package", line 91, in _thread_run
  File "cargo_build in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\Rust Enhanced.sublime-package", line 195, in run
  File "rust.cargo_settings in C:\Users\me\AppData\Roaming\Sublime Text 3\Installed Packages\Rust Enhanced.sublime-package", line 373, in get_command
AttributeError: 'str' object has no attribute 'get'
```

**Comment by ehuss** [comment]
@Boscop Did you restart Sublime?  I think the automatic package updater doesn't always reload the package properly.

**Comment by Boscop** [comment]
@ehuss Now after I restarted Sublime Ctrl-B works again, but the original problem is not fixed, it still interprets the path wrong. rustc 1.25.0-nightly (da569fa9d 2018-01-16)

**Comment by ehuss** [comment]
> it still interprets the path wrong. rustc 1.25.0-nightly (da569fa9d 2018-01-16)

@Boscop look up a few comments, you need 2018-01-19 or newer.

**Comment by Boscop** [comment]
Ah thanks, it works now :)

**Comment by Jayflux** [comment]
Do i need to update the readme with which version of Rust we're supporting now?

**Comment by ehuss** [comment]
> Do i need to update the readme with which version of Rust we're supporting now?

@Jayflux it's up to you, but I don't think it's important.  I try to ensure that things work with reasonably old versions of Rust (at least back to 1.15, check requires 1.16).  Specifying which nightly works is an endless game, since it will break occasionally.  I've thought about setting up CI to catch breaking changes faster, but I think there would be a high risk of false errors (the tests are not as robust as I'd like, and it would be at the mercy of spurious nightly rust problems).

**Comment by Jayflux** [comment]
@ehuss i do think CI would be a great thing, The sublime team are working on exporting their syntax checker as a separate executable so we could run syntax tests on CI, it should be available in their next release, here's an example of them using it here:

**Comment by ehuss** [comment]
@Jayflux The test framework I use (https://github.com/sublimetext/unittesting) actually supports running a full Sublime installation on CI and executing all the tests.  I'll take a look at getting it started sometime soon.

**Pull request merged**
