### PR TITLE
 add 'Updating/Downloading/Documenting/Blocking' to cargo build syntax 

### PR DESCRIPTION
**Pull request by TheIronBorn**

### CODE REVIEW

**Comment by jasonwilliams** [comment]
retry

**Comment by TheIronBorn** [comment]
I've also been thinking about making the text bold to better match rustc's output.  Is is a bad idea to mix text formatting scopes?

**Comment by jasonwilliams** [comment]
sorry @TheIronBorn ive been a bit behind on the PRs lately
If you need to hit me up, im on https://discord.gg/Y2s7m6 in the dev tools team, you can always ping me there

**Comment by jasonwilliams** [comment]
Feel free to make them bold in a separate commit

**Pull request merged**
