### PR TITLE
handle comments around parameters and types in general

### LINKED ISSUE #219: Syntax highlighting fails with custom operators
When using the [mdo crate](https://github.com/TeXitoi/rust-mdo), which uses the custom `=<<` operator, syntax highlighting fails / looks ugly:

Also it fails in this case:

And in cases like this:

### PR DESCRIPTION
**Pull request by dten**
fixes #219 b 
image

### CODE REVIEW

**Comment by dten** [comment]
fixes #219 b 
image

**Comment by Jayflux** [comment]
this is conflicting now @dten

**Comment by dten** [comment]
fixed

**Comment by dten** [comment]
hm maybe hold off i get something weird after rebasing the other change over this

**Comment by dten** [comment]
all good now :)

**Comment by Jayflux** [comment]
conflicting again! @dten

**Comment by dten** [comment]
actually it's gone in into https://github.com/rust-lang/rust-enhanced/commit/56ffe48af6ba177043db808287a5ec54f01ee5a7 because i had done some rebasing

**Pull request closed without merging**
