### PR TITLE
Fix tests.

### PR DESCRIPTION
**Pull request by ehuss**
- Fix for a new message in Rust 1.25.
- Fix a UI test that was expecting items in a specific order, but the order shouldn't matter.

### CODE REVIEW

**Comment by ehuss** [comment]
I don't know why the clippy tests are failing on Linux (they [pass](https://travis-ci.org/ehuss/sublime-rust/builds/340009958) just fine on my repo).  I'll keep investigating.

**Comment by Jayflux** [comment]
Thanks @ehuss  ill leave this PR open then, at least you have a branch and CI to work with now

**Comment by ehuss** [comment]
@Jayflux ok, I think this is ready.  The tests should be a little more stable now.

**Comment by Jayflux** [comment]
Thanks @ehuss what was the problem?

**Comment by ehuss** [comment]
> Thanks @ehuss what was the problem?

Some of the tests depended on the order of the files on the filesystem.  For the Clippy tests, it was running in a project that included targets with errors.  If it compiled the target with errors first, it would early exit, and not compile the file I was using for verifying clippy output.

**Pull request merged**
