### PR TITLE
match large format specs

### PR DESCRIPTION
**Pull request by TheIronBorn**

### CODE REVIEW

**Comment by TheIronBorn** [comment]
The same could be done for escaped chars like `\0`, but I like that they are colored differently than the format spec

**Comment by dten** [comment]
Please can you add a test to https://github.com/rust-lang/rust-enhanced/blob/master/syntax_test_rust.rs

**Comment by TheIronBorn** [comment]
Let me know if it should be a separate test

**Comment by dten** [comment]
yea ideally this should be an extra test, rather than replacing the simple one (which is now technically untested)

**Comment by TheIronBorn** [comment]
Oh yeah, of course.  I'll be right on that

**Comment by dten** [comment]
looks good to me

**Pull request merged**
